POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmluYSIsImlkIjoiNWYyY2VmNTdlZDMyZTE1NzQ0MTQ0MjA2IiwiaWF0IjoxNTk2NzgwNDA2fQ.zE7WP5smzV_ohY7mIRmf4fJy3uGVARl1hmKCQHYyUx0

{
    "title": "Blog made after creating token",
    "author": "Mluukksi",
    "url": "Url1",
    "likes": 1,
    "userId": "5f2cef57ed32e15744144206"
}